language: node_js
node_js:
  - "node"
  - "6"
  - "4"
script: ./node_modules/.bin/jasmine-node test/ && ./node_modules/karma/bin/karma start --single-run --browsers="PhantomJS"
sudo: false
cache:
  directories:
    - node_modules
